In [1]:
import torch
from torch_scatter import scatter

In [2]:
x = torch.randn((9, 4))
cluster = torch.cat((torch.zeros(4), torch.ones(5))).long()
print(x)
print(cluster)

tensor([[ 0.7452,  0.9208, -1.1396,  0.9235],
        [ 1.0136,  1.2251, -1.9326,  0.3186],
        [-0.7062, -0.9951,  0.5675, -0.0863],
        [ 0.3546, -0.2600,  1.1684, -3.2429],
        [-0.5480,  1.0647, -0.3913, -0.8856],
        [-0.5409,  1.1264, -1.6328, -0.8759],
        [-0.0096,  1.3773, -0.0387,  1.4421],
        [ 0.9336, -0.3769,  1.1135,  1.4748],
        [ 0.0505,  0.3634,  0.5885, -0.1368]])
tensor([0, 0, 0, 0, 1, 1, 1, 1, 1])


In [3]:
c = scatter(x, cluster, dim=0, reduce='max')
print(c)
print(c.shape)
print(c[cluster])

tensor([[1.0136, 1.2251, 1.1684, 0.9235],
        [0.9336, 1.3773, 1.1135, 1.4748]])
torch.Size([2, 4])
tensor([[1.0136, 1.2251, 1.1684, 0.9235],
        [1.0136, 1.2251, 1.1684, 0.9235],
        [1.0136, 1.2251, 1.1684, 0.9235],
        [1.0136, 1.2251, 1.1684, 0.9235],
        [0.9336, 1.3773, 1.1135, 1.4748],
        [0.9336, 1.3773, 1.1135, 1.4748],
        [0.9336, 1.3773, 1.1135, 1.4748],
        [0.9336, 1.3773, 1.1135, 1.4748],
        [0.9336, 1.3773, 1.1135, 1.4748]])


In [16]:
# > pytorch 1.12

x = torch.randn((9, 4))

cluster = torch.cat((torch.zeros(4), torch.ones(5))).long().unsqueeze(1).repeat((1,4))

output = torch.zeros((2,4))
out = output.scatter_reduce(0, cluster, x, reduce="amax", include_self=False)

out = out[cluster[:,0]]

"""
In [1]: x
Out[1]: 
tensor([[-1.1713,  0.1483,  2.1248, -0.5578],
        [-0.6092, -1.7833, -0.2607, -0.2200],
        [ 1.8295, -1.1308, -0.2040, -1.4511],
        [ 1.4316, -1.1042,  0.8249, -0.6503],
        [ 1.0343, -1.4297,  1.3399, -0.2548],
        [ 0.6643,  0.1225,  0.8947,  1.6692],
        [ 0.8114,  0.9371, -0.6293,  0.6385],
        [ 0.0514,  0.2745, -0.0692,  0.5211],
        [ 0.0902, -0.4289,  0.2918,  0.4679]])
        
In [2]: cluster
Out[2]: 
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
        
        
In [3]: out[cluster[:,0]]
Out[3]: 
tensor([[ 1.8295,  0.1483,  2.1248, -0.2200],
        [ 1.8295,  0.1483,  2.1248, -0.2200],
        [ 1.8295,  0.1483,  2.1248, -0.2200],
        [ 1.8295,  0.1483,  2.1248, -0.2200],
        [ 1.0343,  0.9371,  1.3399,  1.6692],
        [ 1.0343,  0.9371,  1.3399,  1.6692],
        [ 1.0343,  0.9371,  1.3399,  1.6692],
        [ 1.0343,  0.9371,  1.3399,  1.6692],
        [ 1.0343,  0.9371,  1.3399,  1.6692]])

"""

AttributeError: 'Tensor' object has no attribute 'scatter_reduce'